backend:
  name: github
  repo: osakunta/website
  branch: cms
  api_root: http://localhost:3000/api/github/proxy
  base_url: http://localhost:3000
  auth_endpoint: /api/github/auth
  token_keyword: Bearer
media_folder: public/uploads
public_folder: /uploads
collections:
  - name: "text"
    label: "Text"
    folder: "cms/text"
    create: true
    delete: false
    extension: json
    identifier_field: key
    fields:
      - name: key
        label: "Key"
        widget: string
      - name: fi
        label: "Finnish"
        widget: text
      - name: sv
        label: "Swedish"
        widget: text
      - name: en
        label: "English"
        widget: text
